"""
Pins the numbers the README and its figures state.

The rule this repository follows is that no number appears in the documentation
unless a test holds it in place. The figures in docs/assets/ are generated by
scripts/make_figures.py from a live model, so they cannot drift on their own —
but the prose around them can, and so can the model if someone changes a default.
These tests fail if either happens.
"""
import numpy as np
import pytest
import torch

from model.crf import CRF
from model.seqlabel import SeqLabel
from conftest import shipped_config_data


class TestDimensionFlow:
    """The widths quoted under "The idea in one picture"."""

    @pytest.fixture(scope="class")
    def model(self):
        data = shipped_config_data()
        return data, SeqLabel(data)

    def test_intnet_returns_160(self, model):
        data, seqlabel = model
        assert seqlabel.word_hidden.wordrep.char_feature.output_dim == 160

    def test_word_embeddings_are_100_wide(self, model):
        data, _ = model
        assert data.word_emb_dim == 100

    def test_wordrep_concatenates_to_260(self, model):
        _, seqlabel = model
        assert seqlabel.word_hidden.wordrep.output_dim == 260

    def test_the_main_bilstm_takes_388(self, model):
        _, seqlabel = model
        assert seqlabel.word_hidden.input_size == 388

    def test_the_main_bilstm_emits_256(self, model):
        data, _ = model
        assert data.HP_hidden_dim == 256

    def test_the_widths_actually_add_up(self, model):
        data, seqlabel = model
        sequence = seqlabel.word_hidden
        assert (sequence.wordrep.char_feature.output_dim + data.word_emb_dim
                == sequence.wordrep.output_dim)
        assert (sequence.wordrep.output_dim + data.global_hidden_dim
                == sequence.input_size)


class TestIntNetFormula:
    """The formula the README prints, against the tensor IntNet returns."""

    def test_the_printed_arithmetic_is_right(self):
        char_emb_dim, char_hidden_dim, kernel_type, intNet_layer = 32, 16, 2, 7
        blocks = (intNet_layer - 1) // 2
        assert blocks == 3
        assert char_emb_dim * kernel_type + blocks * char_hidden_dim * kernel_type == 160

    def test_the_old_downstream_formula_agrees_only_at_the_shipped_ratio(self):
        def real(emb, hid, layer=7, kt=2):
            return emb * kt + ((layer - 1) // 2) * hid * kt

        def old(emb, hid, layer=7, kt=2):
            return ((layer - 1) // 2) * hid * kt + hid * 2 * kt

        assert real(32, 16) == old(32, 16) == 160     # shipped: emb == 2 * hidden
        assert real(100, 50) == old(100, 50)          # any other pair on that line
        assert real(8, 8) != old(8, 8)
        assert real(64, 16) != old(64, 16)
        assert real(32, 32) != old(32, 32)


class TestParameterBudget:
    """The claim that two BiLSTMs hold 95% of the weights."""

    @pytest.fixture(scope="class")
    def counts(self):
        data = shipped_config_data()
        model = SeqLabel(data)
        total = sum(p.numel() for p in model.parameters())
        bilstms = sum(p.numel() for name, p in model.named_parameters()
                      if name.startswith("word_hidden.lstm")
                      or name.startswith("word_hidden.sentrep"))
        return total, bilstms

    def test_the_two_bilstms_hold_at_least_95_percent(self, counts):
        total, bilstms = counts
        assert round(100 * bilstms / total) == 95

    def test_every_parameter_lands_in_one_of_the_charted_groups(self):
        # scripts/make_figures.py buckets by prefix; an unmatched parameter would
        # silently vanish from the chart rather than showing up wrong.
        data = shipped_config_data()
        model = SeqLabel(data)
        prefixes = [
            "word_hidden.lstm", "word_hidden.sentrep",
            "word_hidden.wordrep.char_feature", "word_hidden.wordrep.word_embedding",
            "word_hidden.mem_bank", "word_hidden.hidden2tag", "word_hidden.mem2tag",
            "crf.", "word_hidden.wordrep.label_embedding", "word_hidden.label2cnn",
        ]
        unmatched = [name for name, _ in model.named_parameters()
                     if not any(name.startswith(p) for p in prefixes)]
        assert unmatched == []


class TestTransitionMatrix:
    """The count printed on the transition-matrix figure."""

    def test_a_six_tag_crf_pins_28_of_its_64_transitions(self):
        crf = CRF(6, gpu=False)
        matrix = crf.transitions.detach()
        assert matrix.shape == (8, 8)
        assert int((matrix <= -10000.0).sum()) == 28

    def test_the_blocked_cells_are_exactly_the_four_structural_bands(self):
        size = 8
        crf = CRF(size - 2, gpu=False)
        blocked = (crf.transitions.detach() <= -10000.0).numpy()

        expected = np.zeros((size, size), dtype=bool)
        expected[0, :] = expected[:, 0] = True       # padding
        expected[:, size - 2] = True                 # nothing enters START
        expected[size - 1, :] = True                 # nothing leaves STOP
        assert np.array_equal(blocked, expected)


class TestFigureScriptStaysRunnable:
    """
    Skipped when matplotlib is absent: the figures are a documentation artefact,
    not something training or decoding depends on.
    """

    @pytest.fixture(autouse=True)
    def _needs_matplotlib(self):
        pytest.importorskip("matplotlib")

    def test_every_figure_builder_is_registered(self):
        from scripts import make_figures
        names = {fn.__name__ for fn in make_figures.FIGURES}
        assert names == {
            "figure_intnet_width",
            "figure_dimension_flow",
            "figure_parameter_budget",
            "figure_crf_transitions",
            "figure_viterbi_vs_brute_force",
            "figure_tag_schemes",
        }

    def test_both_themes_are_defined_with_the_keys_the_styler_reads(self):
        from scripts import make_figures
        assert set(make_figures.THEMES) == {"light", "dark"}
        for palette in make_figures.THEMES.values():
            assert set(palette) == {"bg", "fg", "muted", "grid"}

    def test_the_measured_width_helper_agrees_with_the_declared_one(self):
        from scripts.make_figures import intnet_width_measured
        # The helper asserts this internally; calling it is the check.
        assert intnet_width_measured(32, 16, 7) == 160
